queues:
  na-practice:

    fancyName: "NA Practice"
    serverName: "na-hub-02"
    children:
      fast-pass:
        fancyName: "Fast Pass"
        permission: "queue.lanes.fastpass"
        priority: 1
