queues:
  GrowlyX:
    fancyName: "Master Growly"
    serverName: "growly-server"
    children:
      nv6:
        fancyName: "Coder Nv6"
        priority: 1
      staud:
        fancyName: "noob staud"
        priority: 99502947359
