server-id: "something-something"
queues:
  na-practice:
    fancyName: "NA Practice"
    serverName: "na-hub-02"
    children:
      fast-pass:
        fancyName: "Fast Pass"
        permission: "queue.lanes.fastpass"
        priority: 1
redis:
  host: "127.0.0.1"
  port: 6379
  authentication:
    enabled: false
    password: ""
priorities:
  - permission:weight
  - scandium.staff:100
