# Queue servers - should match all other servers
queues:
  na-practice:
    fancyName: "NA Practice"
    serverName: "hub-2"
    children:
      fast-pass:
        fancyName: "Fast Pass"
        permission: "queue.lanes.fastpass"
        priority: 1
# server-specific data - Only needed if you aren't using Lemon
server-id: "something-something"
redis:
  host: "127.0.0.1"
  port: 6379
  authentication:
    enabled: false
    password: ""
# Per-player priorities - Format them like this: permission:weight
priorities:
  - permission:weight
  - lemon.staff:100
